---
- name: "Aws Infrastructure using ansible"
  hosts: localhost
  become: true

  tasks:
    - name: Basic deploy of a service
      community.general.terraform:
        project_path: "./terr/"
        state: present
        force_init: true
      register: inst

    - name: "Print the Public IPs"
      debug:
        msg: "Instance-Id : {{ item }}"
      with_items: "{{ inst.outputs.instance.value }}"

    - name: "Creating Dynamic Inventory"
      add_host:
        hostname: '{{ item }}'
        groups: "backend"
        ansible_host: '{{ item }}'
        ansible_port: 22
        ansible_user: "ec2-user"  
        ansible_ssh_private_key_file: "ansible.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
        - "{{ inst.outputs.instance.value }}"


- name: "Deployment From GitHub"
  hosts: backend
  become: true
  serial: 1
  vars:
    packages:
      - httpd
      - php
      - git
    repo: https://github.com/mithrams07/aws-elb-site.git
  tasks:

    - name: "Package Installation"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Clonning Github Repository {{ repo }}"
      git:
        repo: "{{ repo }}"
        dest: "/var/website/"
      register: gitstatus

    - name: "Backend off loading from elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0000

    - name: "waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 30

    - name: "updating site contents"
      when: gitstatus.changed
      copy:
        src: "/var/website/"
        dest: "/var/www/html/"
        remote_src: true
        owner: apache
        group: apache

    - name: "loading backend to elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0644

    - name: "waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 20
